version: '3'

services:
  dev:
    container_name: wpp-bot-dev
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./src/server.js:/server.js
    ports:
      - '8080:8080'
   

  prod:
    container_name: wpp-bot-prod
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '8883:8883'
    
      




