-- AlterTable
ALTER TABLE "fuel" ADD COLUMN     "fuel_created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "fuel_updated_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "set_variables" ADD COLUMN     "set_created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "set_updated_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
